<a href="https://colab.research.google.com/github/sighthon/pytorch_notes/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu121


## Introduction to tensors


### Creating Tensors

Pytorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim # scalar has no dimensions

0

In [4]:
# Get tensor back as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX : Matrixes and Tensors are names UPPERCASE

MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [16]:
TENSOR[0][0]

tensor([1, 2, 3])

In [17]:
# TENSOR = torch.tensor([[1,2], [1,2,3]])
# doesn't work
# Tensors has to follow same size within a dimension

### Random tensors

Why random tensors?
Random tensors are important beacuse the way many NN learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [18]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4,5)
random_tensor

tensor([[[0.9991, 0.8044, 0.2009, 0.0727, 0.6889],
         [0.6274, 0.8654, 0.3655, 0.9149, 0.3048],
         [0.4081, 0.3330, 0.0266, 0.7581, 0.8232],
         [0.2855, 0.4550, 0.5836, 0.2645, 0.1689]],

        [[0.3858, 0.3410, 0.7245, 0.9335, 0.3445],
         [0.9288, 0.7927, 0.9507, 0.5348, 0.2624],
         [0.2926, 0.1074, 0.1266, 0.9672, 0.1622],
         [0.4912, 0.9885, 0.7228, 0.9816, 0.1695]],

        [[0.8891, 0.3099, 0.1817, 0.2032, 0.9206],
         [0.5904, 0.5224, 0.4891, 0.5029, 0.7824],
         [0.1653, 0.0519, 0.3703, 0.9318, 0.9180],
         [0.1600, 0.4898, 0.5256, 0.1827, 0.5377]]])

In [19]:
# Random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 5, 5)) # color channels, height, width
random_image_size_tensor

tensor([[[0.1887, 0.5955, 0.4718, 0.2577, 0.1548],
         [0.6581, 0.9684, 0.3904, 0.6687, 0.9229],
         [0.1620, 0.9531, 0.3216, 0.7991, 0.7695],
         [0.1379, 0.2186, 0.4504, 0.4478, 0.1894],
         [0.7300, 0.5584, 0.0431, 0.1612, 0.9790]],

        [[0.1861, 0.3038, 0.6972, 0.1290, 0.9909],
         [0.0027, 0.9807, 0.1784, 0.6548, 0.5932],
         [0.3161, 0.4630, 0.0136, 0.8514, 0.7731],
         [0.5945, 0.4017, 0.1268, 0.8211, 0.5302],
         [0.1820, 0.6902, 0.1829, 0.4724, 0.4410]],

        [[0.1634, 0.8239, 0.3111, 0.5871, 0.1237],
         [0.2169, 0.8956, 0.0309, 0.3306, 0.0521],
         [0.8087, 0.5924, 0.6011, 0.1885, 0.5579],
         [0.0409, 0.9340, 0.5690, 0.0335, 0.3388],
         [0.9951, 0.0731, 0.9254, 0.5831, 0.9402]]])

### Zeros and ones

In [20]:
# Create a tnsor of zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype # datatype of data in tensor

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
# torch.range() might probably be deprecated
one_to_ten = torch.arange(start=0, end=1000, step=77) # will finish at end -1
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [24]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run with pytorch
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # datatype: float32, float64
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients on
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [30]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Geting info from tensors

1) datatype - `tensor.dtype`
2) shape - `tensor.shape`
3) device - `tensor.device`


In [31]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4297, 0.3737, 0.8236, 0.5240],
        [0.2079, 0.3061, 0.4340, 0.9361],
        [0.2679, 0.3070, 0.1623, 0.7468]])

In [32]:
print(some_tensor.size())
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.device)

torch.Size([3, 4])
torch.Size([3, 4])
torch.float32
cpu


### Manipulating Tensors

Tensor operations include:
* addition
* substraction
* multiplication (element-wise)
* division
* matrix multiplication


In [33]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [34]:
tensor * 10

tensor([10, 20, 30])

In [35]:
tensor - 10

tensor([-9, -8, -7])

In [36]:
# inbuilt function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [37]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [38]:
torch.div(tensor, 2)

tensor([0.5000, 1.0000, 1.5000])

### Matrix Multiplication
2 main ways of performing MM
* Element wise - torch.mul
* matrix multiplication - dot product

There are 2 main rules to be satisfied:
1. The **inner dimensions** should match
* `(3,2) @ (3,2)` doesn't work
* `(2,3) @ (3,2)` will work

2. The resulting matrix has shape of outer dimensions.
* `(2,3) @ (3,2)` will have shape of `(2,2)`

In [39]:
ten = torch.tensor([1, 2, 3])


In [40]:
# Element wise multiplication
ten * ten

tensor([1, 4, 9])

In [41]:
torch.matmul(ten, ten) # 1*1 + 2*2 + 3*3

tensor(14)

In [42]:
ten1 = torch.tensor([[1, 2], [3, 4]])
print(ten1.size())
ten1

torch.Size([2, 2])


tensor([[1, 2],
        [3, 4]])

In [43]:
ten2 = torch.tensor([[5, 6], [7, 8], [9,10]])
print(ten2.size())
ten2

torch.Size([3, 2])


tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [44]:
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x2 and 3x2)
try:
  ten3 = torch.matmul(ten1, ten2)
  print(ten3)
except RuntimeError as e:
  print(e)

mat1 and mat2 shapes cannot be multiplied (2x2 and 3x2)
